name: Deploy to AWS Lambda

on:
  push:
    branches:
      - release/*

env:
  RELEASE_NAME: ${GITHUB_REF##*release/}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: echo some values
        run: |
          echo "${GITHUB_REF}"
          echo "${GITHUB_REF##*release/}"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      
      - name: Install Dependencies
        run: |
          npm ci
          npm install -g serverless
      
      - name: Deploy to AWS Lambda using serverless framework
        run: |
          RELEASE_NAME=${GITHUB_REF##*release/}
          serverless deploy --stage=${RELEASE_NAME}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}