name: matrix-strategy

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          - platform: macos-latest
            node-version: 14
      fail-fast: false
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install Dependencies
        run: npm install

      - name: Build and Test
        run: npm run build && npm run test
        continue-on-error: true

