name: My First Workflow

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Print a message
        run: echo "Hello, world!"

        