name: use_custom_action

on:
  pull_request:
    branches:
      - master

jobs:
  get-timestamp:
    runs-on: ubuntu-latest
    name: get the timestamp for the business greeting
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: fetch name
        id: get_timestamp
        uses: .
        with:
          name: 'Aayush'
      
      - name: print the timestamp
        run: echo "${{ steps.get_timestamp.outputs.timestamp }}"
